spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/videocall
spring.datasource.username=umarfiroz
spring.datasource.password=user1234


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.app.jwtSecret=7mK2pQ9xL4vN8rT1aB6yH3wZ5cD7eF0gsdsdsd
spring.app.jwtExpirationMs=86400000